### ISSUE TITLE
read auto offset from configuration

### ISSUE THREAD

**Issue by MehmetFiratKomurcu** [Trendyol/kafka-retry-job#23]
We can give the user a start offset option. We can read the config and decide whether to start from the oldest or latest offset.

**Comment by ahmetfurkankavraz** [comment]
Can you explain it more detailly?

In general, there 3 offsets in Kafka:
- Earliest
- Latest
- Last-committed 

Last-committed offsets are specific for each consumer group, meanwhile the others are specific for each topic.

I think, you meant to select either Earliest or Last-committed. Because using Latest won't be effective, since there will be only one message consumption.

**Comment by MehmetFiratKomurcu** [comment]
earlist and latest's are belong to consumer groups. check out: https://kafka.apache.org/documentation/#consumerconfigs_auto.offset.reset

**Comment by MehmetFiratKomurcu** [comment]
no need it for now.
